version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:5.1.2
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_MESSAGE_MAX_BYTES: 50000012
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
#    ports:
#      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  schema-registry:
    image: confluentinc/cp-schema-registry:5.1.2
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
    depends_on:
      - zookeeper
