/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.sysco.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Common extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2309986745232226444L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Common\",\"namespace\":\"no.sysco.avro\",\"fields\":[{\"name\":\"field\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Common> ENCODER =
      new BinaryMessageEncoder<Common>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Common> DECODER =
      new BinaryMessageDecoder<Common>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Common> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Common> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Common>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Common to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Common from a ByteBuffer. */
  public static Common fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Common() {}

  /**
   * All-args constructor.
   * @param field The new value for field
   */
  public Common(java.lang.CharSequence field) {
    this.field = field;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'field' field.
   * @return The value of the 'field' field.
   */
  public java.lang.CharSequence getField() {
    return field;
  }

  /**
   * Sets the value of the 'field' field.
   * @param value the value to set.
   */
  public void setField(java.lang.CharSequence value) {
    this.field = value;
  }

  /**
   * Creates a new Common RecordBuilder.
   * @return A new Common RecordBuilder
   */
  public static no.sysco.avro.Common.Builder newBuilder() {
    return new no.sysco.avro.Common.Builder();
  }

  /**
   * Creates a new Common RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Common RecordBuilder
   */
  public static no.sysco.avro.Common.Builder newBuilder(no.sysco.avro.Common.Builder other) {
    return new no.sysco.avro.Common.Builder(other);
  }

  /**
   * Creates a new Common RecordBuilder by copying an existing Common instance.
   * @param other The existing instance to copy.
   * @return A new Common RecordBuilder
   */
  public static no.sysco.avro.Common.Builder newBuilder(no.sysco.avro.Common other) {
    return new no.sysco.avro.Common.Builder(other);
  }

  /**
   * RecordBuilder for Common instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Common>
    implements org.apache.avro.data.RecordBuilder<Common> {

    private java.lang.CharSequence field;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.sysco.avro.Common.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.field)) {
        this.field = data().deepCopy(fields()[0].schema(), other.field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Common instance
     * @param other The existing instance to copy.
     */
    private Builder(no.sysco.avro.Common other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.field)) {
        this.field = data().deepCopy(fields()[0].schema(), other.field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'field' field.
      * @return The value.
      */
    public java.lang.CharSequence getField() {
      return field;
    }

    /**
      * Sets the value of the 'field' field.
      * @param value The value of 'field'.
      * @return This builder.
      */
    public no.sysco.avro.Common.Builder setField(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'field' field has been set.
      * @return True if the 'field' field has been set, false otherwise.
      */
    public boolean hasField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'field' field.
      * @return This builder.
      */
    public no.sysco.avro.Common.Builder clearField() {
      field = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Common build() {
      try {
        Common record = new Common();
        record.field = fieldSetFlags()[0] ? this.field : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Common>
    WRITER$ = (org.apache.avro.io.DatumWriter<Common>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Common>
    READER$ = (org.apache.avro.io.DatumReader<Common>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
